/*
DATABASE EXPLORATION
*/

/*EXPLORE ALL OBJECT IN THE DATA BASE*/

SELECT * FROM INFORMATION_SCHEMA.TABLES

/*EXPLORE ALL COLUMNS IN THE DATA BASE*/

SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME ='dim_customers'
